Repository mash-up-kr/NoWeekend-iOS, pull requests merged in 2025-07, with the labels that each got.

#65 [Feat/#62] 할일CRUD API 연동 및 할일추가 애니메이션 추가
  Projects/Calendar/CalendarData/Sources/DTOs/CreateScheduleRequestDTO.swift
  Projects/Calendar/CalendarData/Sources/DTOs/DeleteScheduleResponseDTO.swift
  Projects/Calendar/CalendarData/Sources/DTOs/UpdateScheduleRequestDTO.swift
  Projects/Calendar/CalendarData/Sources/Repositories/CalendarRepositoryImpl.swift
  Projects/Calendar/CalendarDomain/Sources/Repositories/CalendarRepositoryProtocol.swift
  Projects/Calendar/CalendarDomain/Sources/Repositories/CreateScheduleRequest.swift
  Projects/Calendar/CalendarDomain/Sources/Repositories/UpdateScheduleRequest.swift
  Projects/Calendar/CalendarDomain/Sources/UseCase/CalendarUseCase.swift
  Projects/Calendar/CalendarDomain/Sources/UseCase/CalendarUseCaseProtocol.swift
  Projects/Calendar/CalendarFeature/Sources/Views/Components/FloatingAddButton.swift
  Projects/Calendar/CalendarFeature/Sources/Views/Todo/TaskCategorySelectionView.swift
  Projects/Calendar/CalendarFeature/Sources/Views/Todo/TodoScrollSection.swift
  Projects/Calendar/CalendarFeature/Sources/Views/View/CalendarView.swift
  Projects/Login/LoginDomain/Sources/UseCase/Impl/GoogleLoginUseCase.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icn_xmark.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icn_xmark.imageset/icn_xmark.svg
  Projects/Shared/DesignSystem/Sources/UIComponents/TodoList/TodoCheckboxComponent.swift
Labels: style, feature, jihoon

#68 [Feat/#44] home view
  Projects/Feature/Calendar/Sources/CalendarSection.swift
  Projects/Feature/Calendar/Sources/CalendarView.swift
  Projects/Feature/Calendar/Sources/FloatingAddButton.swift
  Projects/Feature/Calendar/Sources/MonthCalendarView.swift
  Projects/Feature/Calendar/Sources/TaskEditSheetView.swift
  Projects/Feature/Calendar/Sources/TodoItem.swift
  Projects/Feature/Calendar/Sources/TodoScrollSection.swift
  Projects/Feature/Home/Sources/HomeView.swift
  Projects/Feature/Profile/Sources/ProfileView.swift
  Projects/Feature/TabBar/Sources/TabBarView.swift
  Projects/Home/HomeData/Sources/EventRepositoryImpl.swift
  Projects/Home/HomeData/Sources/HomeDataModule.swift
  Projects/Home/HomeData/Sources/HomeRepositoryImpl.swift
  Projects/Home/HomeDomain/Sources/Entities/Event.swift
  Projects/Home/HomeDomain/Sources/Entities/Home.swift
  Projects/Home/HomeDomain/Sources/RepositoryInterfaces/EventRepositoryProtocol.swift
  Projects/Home/HomeDomain/Sources/RepositoryInterfaces/HomeRepositoryProtocol.swift
  Projects/Home/HomeDomain/Sources/UseCases/EventUseCaseProtocol.swift
  Projects/Home/HomeDomain/Sources/UseCases/HomeUseCase.swift
  Projects/Home/HomeDomain/Sources/UseCases/HomeUseCaseProtocol.swift
  Projects/Home/HomeFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Home/HomeFeature/Demo/Sources/HomeDemoApp.swift
  Projects/Home/HomeFeature/Project.swift
  Projects/Home/HomeFeature/Sources/Assembly/HomeFeatureAssembly.swift
  Projects/Home/HomeFeature/Sources/Assembly/HomeFeatureModule.swift
  Projects/Home/HomeFeature/Sources/EventUseCase.swift
  Projects/Home/HomeFeature/Sources/HomeCoordinator.swift
  Projects/Home/HomeFeature/Sources/HomeCoordinatorView.swift
  Projects/Home/HomeFeature/Sources/HomeView.swift
  Projects/Home/HomeFeature/Sources/Store/HomeModels.swift
  Projects/Home/HomeFeature/Sources/Store/HomeStore.swift
  Projects/Home/HomeFeature/Sources/Store/Model/VacationCardItem.swift
  Projects/Home/HomeFeature/Sources/Views/Components/CardPageControl.swift
  Projects/Home/HomeFeature/Sources/Views/Components/LongCardSection.swift
  Projects/Home/HomeFeature/Sources/Views/Components/MainTopView.swift
  Projects/Home/HomeFeature/Sources/Views/Components/ShortCardSection.swift
  Projects/Home/HomeFeature/Sources/Views/Components/VacationCardView.swift
  Projects/Home/HomeFeature/Sources/Views/Components/WeekVacation.swift
  Projects/Home/HomeFeature/Sources/Views/Extensions/VacationCardType+UI.swift
  Projects/Home/HomeFeature/Sources/Views/HomeView.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icn_home_off.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icn_home_off.imageset/icn_Home_Off.svg
Labels: nahee, feature

#73 [Feat/#72] 캘린더뷰화면연결 및 API연결
  Projects/App/Sources/AppState.swift
  Projects/App/Sources/DI/AppDependencyConfiguration.swift
  Projects/App/Sources/Tabbar/TabBarView.swift
  Projects/Calendar/CalendarData/Sources/DTOs/DailyScheduleDTO.swift
  Projects/Calendar/CalendarDomain/Sources/DailySchedule.swift
  Projects/Calendar/CalendarDomain/Sources/UseCase/CalendarUseCase.swift
  Projects/Calendar/CalendarFeature/Sources/Coordinator/CalendarCoordinator.swift
  Projects/Calendar/CalendarFeature/Sources/Views/Add Task  /TaskCreateView.swift
  Projects/Calendar/CalendarFeature/Sources/Views/Add Task  /TaskDetailView.swift
  Projects/Calendar/CalendarFeature/Sources/Views/Calendar/MonthCalendarView.swift
  Projects/Calendar/CalendarFeature/Sources/Views/Todo/TaskCategorySelectionView.swift
  Projects/Calendar/CalendarFeature/Sources/Views/View/CalendarView.swift
  Projects/Core/NWNetwork/Sources/NetworkService/NWNetworkService.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icn_home_off.imageset/Contents.json
  Projects/Shared/DesignSystem/Sources/UIComponents/BottomSheet/DatePicker/DatePickerWithLabelBottomSheet.swift
  Projects/Shared/DesignSystem/Sources/UIComponents/Calendar/calendarComponent.swift
  graph.png
Labels: feature, jihoon

#86 [Feat/#83] 위치 권한 관련 플로우 적용
  Projects/App/Info.plist
  Projects/App/Sources/Tabbar/TabBarView.swift
  Projects/Home/HomeFeature/Sources/Home/Components/WeekVacation.swift
  Projects/Home/HomeFeature/Sources/Home/HomeModels.swift
  Projects/Home/HomeFeature/Sources/Home/HomeStore.swift
  Projects/Home/HomeFeature/Sources/Home/HomeView.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icn_location.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icn_location.imageset/icn_location.svg
  Projects/Shared/Project.swift
  Projects/Shared/Utils/Sources/Location/LocationInfo.swift
  Projects/Shared/Utils/Sources/Location/LocationManager.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+extensions.swift
Labels: nahee, feature

#90 Feat/#84 Profile 구현
  Projects/App/Project.swift
  Projects/App/Sources/AppFlow.swift
  Projects/App/Sources/AppState.swift
  Projects/App/Sources/ContentView.swift
  Projects/App/Sources/Coordinator/AppCoordinator.swift
  Projects/App/Sources/Coordinator/AppCoordinatorView.swift
  Projects/App/Sources/Coordinator/AppRouter.swift
  Projects/App/Sources/Coordinator/CoordinatorFactory.swift
  Projects/App/Sources/DI/AppDependencyConfiguration.swift
  Projects/App/Sources/NoWeekendApp.swift
  Projects/App/Sources/Tabbar/TabBarView.swift
  Projects/Core/NWNetwork/Sources/NetworkService/NWNetworkService.swift
  Projects/Core/NWNetwork/Sources/TokenManager.swift
  Projects/Core/Project.swift
  Projects/Login/LoginData/Sources/Assembly/LoginDataModule.swift
  Projects/Login/LoginData/Sources/DTO/Request/GoogleLoginRequestDTO.swift
  Projects/Login/LoginData/Sources/DTO/Response/GoogleLoginResponseDTO.swift
  Projects/Login/LoginData/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Login/LoginDomain/Sources/Repository/AuthRepositoryInterface.swift
  Projects/Login/LoginDomain/Sources/Service/AppleAuthServiceInterface.swift
  Projects/Login/LoginDomain/Sources/UseCase/Impl/GoogleLoginUseCase.swift
  Projects/Login/LoginFeature/Sources/Assembly/LoginFeatureAssembly.swift
  Projects/Login/LoginFeature/Sources/Store/LoginStore.swift
  Projects/Onboarding/OnboardingData/Sources/DTO/OnboardingResponseDTO.swift
  Projects/Onboarding/OnboardingData/Sources/Endpoint/OnboardingEndpoint.swift
  Projects/Onboarding/OnboardingData/Sources/Service/OnboardingNetworkService.swift
  Projects/Onboarding/OnboardingFeature/Sources/Store/OnboardingStore.swift
  Projects/Onboarding/OnboardingFeature/Sources/View/OnboardingView.swift
  Projects/Profile/ProfileData/Sources/DTO/ProfileMapper.swift
  Projects/Profile/ProfileData/Sources/DTO/UserProfileDTO.swift
  Projects/Profile/ProfileFeature/Project.swift
  Projects/Profile/ProfileFeature/Sources/Assembly/ProfileFeatureAssembly.swift
  Projects/Profile/ProfileFeature/Sources/Store/ProfileEditStore.swift
  Projects/Profile/ProfileFeature/Sources/Store/ProfileStore.swift
  Projects/Profile/ProfileFeature/Sources/View/ProfileDetail/ProfileEditView.swift
  Projects/Profile/ProfileFeature/Sources/View/ProfileDetail/ProfileTagsView.swift
  Projects/Shared/Derived/Sources/TuistBundle+DesignSystem.swift
Labels: feature, sijong

#88 [Feat/#84] 캘린더피쳐마무리할라했는데실패
  Projects/Calendar/CalendarFeature/Sources/Views/View/CalendarStore.swift
  Projects/Home/HomeFeature/Sources/Home/Components/WeekVacation.swift
  Projects/Home/HomeFeature/Sources/Home/HomeStore.swift
  Projects/Home/HomeFeature/Sources/Home/HomeView.swift
Labels: feature, jihoon

#119 Onboarding, Profile QA 수정사항
  Projects/App/Sources/ContentView.swift
  Projects/App/Sources/Coordinator/AppCoordinator.swift
  Projects/Onboarding/OnboardingData/Sources/DTO/OnboardingStatusResponseDTO.swift
  Projects/Onboarding/OnboardingData/Sources/Endpoint/OnboardingEndpoint.swift
  Projects/Onboarding/OnboardingData/Sources/Service/OnboardingNetworkService.swift
  Projects/Onboarding/OnboardingDomain/Sources/Service/OnboardingNetworkServiceInterface.swift
  Projects/Onboarding/OnboardingFeature/Sources/Store/OnboardingStore.swift
  Projects/Onboarding/OnboardingFeature/Sources/View/OnboardingView.swift
  Projects/Profile/ProfileData/Sources/Service/ProfileNetworkServiceInterface.swift
  Projects/Profile/ProfileFeature/Sources/View/ProfileView.swift
  Projects/Shared/DesignSystem/Sources/UIComponents/NWUserInput/NWUserInputSection.swift
Labels: fix, sijong

#125 [Feat/#124] TMA 구조로 변경
  Projects/Calendar/CalendarFeature/Example/Sources/CalendarExampleApp.swift
  Projects/Calendar/CalendarFeature/Example/Sources/MockCalendarRepository.swift
  Projects/Calendar/CalendarFeature/Project.swift
  Projects/Calendar/CalendarFeature/Sources/Views/View/CalendarModels.swift
  Projects/Calendar/CalendarFeature/Tests/CalendarFeatureTests.swift
  graph.png
Labels: jihoon

#128 [Feat/#126] 캘린더테스트코드작성
  Projects/Calendar/CalendarFeature/Tests/CalendarDomainTests.swift
  Projects/Calendar/CalendarFeature/Tests/CalendarFeatureOnlyTests.swift
  Projects/Calendar/CalendarFeature/Tests/CalendarFeatureTests.swift
  Projects/Calendar/CalendarFeature/Tests/CalendarIntegrationTests.swift
  Projects/Calendar/CalendarFeature/Tests/MockCalendarRepository.swift
Labels: jihoon
